# -*- coding: utf-8 -*-
"""Dhallah_AI_Engine.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KVuYDmmiT6wIXofqBqXkhmfZb4q7oNbm
"""

!pip install -q firebase-admin
!pip install -q torch torchvision torchaudio
!pip install -q transformers sentence-transformers
!pip install -q qdrant-client
!pip install -q Pillow requests
!pip install -q colorama

print("All required packages have been installed successfully!")

import firebase_admin
from firebase_admin import credentials
from firebase_admin import firestore
import requests
from PIL import Image
from io import BytesIO

cred_path = '/content/dhallahapp-firebase-adminsdk-fbsvc-a887b54b43.json'
try:
    if not firebase_admin._apps:
        cred = credentials.Certificate(cred_path)
        firebase_admin.initialize_app(cred)
    print("Firebase initialized successfully.\n")
except Exception as e:
    print(f"Firebase initialization failed: {e}")

db = firestore.client()

def deep_profile_reports(collection_name='reports'):
    print(f"--- Deep Profiling '{collection_name}' Collection ---\n")

    lost_docs = db.collection(collection_name).where('type', '==', 'lost').limit(2).stream()
    print(">>> Sample 'LOST' Reports:")
    for doc in lost_docs:
        print(f"ID: {doc.id}")
        data = doc.to_dict()
        for key, value in data.items():
            print(f"  - {key} ({type(value).__name__}): {value}")
        print("-" * 20)

    found_docs = db.collection(collection_name).where('type', '==', 'found').limit(2).stream()
    print("\n>>> Sample 'FOUND' Reports:")
    for doc in found_docs:
        print(f"ID: {doc.id}")
        data = doc.to_dict()
        for key, value in data.items():
            print(f"  - {key} ({type(value).__name__}): {value}")
        print("-" * 20)

deep_profile_reports()

import os
import torch
from transformers import AutoImageProcessor, AutoModel
from sentence_transformers import SentenceTransformer
from qdrant_client import QdrantClient
from qdrant_client.models import Distance, VectorParams

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Using device: {device}")

# 1. Initialize Image Model (DINOv2)
print("Loading DINOv2 model...")
image_processor = AutoImageProcessor.from_pretrained('facebook/dinov2-small')
image_model = AutoModel.from_pretrained('facebook/dinov2-small').to(device)
print("DINOv2 model loaded successfully.")

# 2. Initialize Text Model (Multilingual MiniLM)
print("Loading Text model...")
text_model = SentenceTransformer('paraphrase-multilingual-MiniLM-L12-v2', device=device)
print("Text model loaded successfully.")

# 3. Initialize Local Qdrant Database
qdrant_path = "./local_dalla_db"
client = QdrantClient(path=qdrant_path)

collection_name = "reports_collection"

# Configure Named Vectors (one for image, one for text)
vectors_config = {
    "image": VectorParams(size=384, distance=Distance.COSINE),
    "text": VectorParams(size=384, distance=Distance.COSINE)
}

if not client.collection_exists(collection_name):
    client.create_collection(
        collection_name=collection_name,
        vectors_config=vectors_config
    )
    print(f"Qdrant collection '{collection_name}' created successfully with named vectors.")
else:
    print(f"Qdrant collection '{collection_name}' already exists and is ready.")

import numpy as np
import requests
from PIL import Image
from io import BytesIO

def extract_image_features(image_url):
    if not image_url:
        return None

    try:
        response = requests.get(image_url, timeout=10)
        if response.status_code != 200:
            print(f"Failed to fetch image. Status: {response.status_code}")
            return None

        image = Image.open(BytesIO(response.content)).convert('RGB')
        inputs = image_processor(images=image, return_tensors="pt").to(device)

        with torch.no_grad():
            outputs = image_model(**inputs)
            # Extract CLS token (first token of the last hidden state)
            embedding = outputs.last_hidden_state[:, 0, :].cpu().numpy()[0]

        # L2 Normalization for Cosine Similarity
        normalized_embedding = embedding / np.linalg.norm(embedding)
        return normalized_embedding.tolist()

    except Exception as e:
        print(f"Image extraction error: {e}")
        return None

def build_rich_text(item_dict):
    if not isinstance(item_dict, dict):
        return ""

    parts = []
    # Order matters slightly for context: Category -> Color -> Description -> Features
    if 'category' in item_dict and item_dict['category']:
        parts.append(item_dict['category'])
    if 'color' in item_dict and item_dict['color']:
        parts.append(item_dict['color'])
    if 'description' in item_dict and item_dict['description']:
        parts.append(item_dict['description'])
    if 'uniqueFeatures' in item_dict and item_dict['uniqueFeatures']:
        parts.append(item_dict['uniqueFeatures'])

    return " ".join(parts)

def extract_text_features(text_input):
    if not text_input or text_input.strip() == "":
        return None

    try:
        # MiniLM supports built-in normalization
        vector = text_model.encode(text_input, normalize_embeddings=True)
        return vector.tolist()
    except Exception as e:
        print(f"Text extraction error: {e}")
        return None

print("Extractor functions defined successfully.")

import uuid
from qdrant_client.models import PointStruct, Filter, FieldCondition, MatchValue

def generate_qdrant_id(firebase_id):
    return str(uuid.uuid5(uuid.NAMESPACE_OID, firebase_id))

# Updated indexing function to include 'status' in the payload
def index_report_to_qdrant(firebase_id, item_dict, report_type, user_id, report_status="open"):
    qdrant_id = generate_qdrant_id(firebase_id)

    image_url = item_dict.get('imageURL')
    img_vector = extract_image_features(image_url) if image_url else None

    rich_text = build_rich_text(item_dict)
    text_vector = extract_text_features(rich_text)

    vectors_dict = {}
    if img_vector:
        vectors_dict["image"] = img_vector
    if text_vector:
        vectors_dict["text"] = text_vector

    if not img_vector:
        print(f"[QDRANT] Skipped {firebase_id}: Image vector is mandatory for Dhallah.")
        return False

    client.upsert(
        collection_name=collection_name,
        points=[
            PointStruct(
                id=qdrant_id,
                vector=vectors_dict,
                payload={
                    "firebase_id": firebase_id,
                    "type": report_type,
                    "userId": user_id,
                    "has_image": bool(img_vector),
                    "status": report_status # updated payload to include status
                }
            )
        ]
    )
    print(f"[QDRANT] Successfully indexed {firebase_id} ({report_type}).")
    return True
# End of update

print("Indexing function updated to support status payload.")

from qdrant_client.models import Filter, FieldCondition, MatchValue

def search_weighted_matches(item_dict, current_type, current_user_id, top_k=3):
    target_type = "found" if current_type == "lost" else "lost"

    # Updated filter to include only open reports of the opposite type
    must_conditions = [
        FieldCondition(key="type", match=MatchValue(value=target_type)),
        FieldCondition(key="status", match=MatchValue(value="open"))
    ]
    # end of update

    must_not_conditions = []
    if current_user_id and current_user_id != 'unknown':
        must_not_conditions.append(
            FieldCondition(key="userId", match=MatchValue(value=current_user_id))
        )

    type_filter = Filter(
        must=must_conditions,
        must_not=must_not_conditions
    )

    image_url = item_dict.get('imageURL')
    query_img_vector = extract_image_features(image_url) if image_url else None

    rich_text = build_rich_text(item_dict)
    query_txt_vector = extract_text_features(rich_text)

    combined_scores = {}
    use_query_points = hasattr(client, 'query_points')

    print(f"[SEARCH] Querying Qdrant for opposite type: {target_type}...")

    if query_img_vector and query_txt_vector:
        if use_query_points:
            img_hits = client.query_points(collection_name=collection_name, query=query_img_vector, using="image", query_filter=type_filter, limit=10).points
        else:
            img_hits = client.search(collection_name=collection_name, query_vector=("image", query_img_vector), query_filter=type_filter, limit=10)

        for hit in img_hits:
            fb_id = hit.payload['firebase_id']
            weighted_img_score = hit.score * 0.8
            combined_scores[fb_id] = combined_scores.get(fb_id, 0) + (hit.score * 0.8)
            print(f"{Fore.CYAN}[DEBUG] Image Match for {fb_id}: Raw={hit.score:.2f}, Weighted(80%)={weighted_img_score:.2f}")
        if use_query_points:
            txt_hits = client.query_points(collection_name=collection_name, query=query_txt_vector, using="text", query_filter=type_filter, limit=10).points
        else:
            txt_hits = client.search(collection_name=collection_name, query_vector=("text", query_txt_vector), query_filter=type_filter, limit=10)

        for hit in txt_hits:
            fb_id = hit.payload['firebase_id']
            weighted_txt_score = hit.score * 0.2
            combined_scores[fb_id] = combined_scores.get(fb_id, 0) + (hit.score * 0.2)
            print(f"{Fore.MAGENTA}[DEBUG] Text Match for {fb_id}: Raw={hit.score:.2f}, Weighted(20%)={weighted_txt_score:.2f}")
    sorted_results = sorted(combined_scores.items(), key=lambda item: item[1], reverse=True)[:top_k]

    formatted_results = [
        {"matched_report_id": fb_id, "score": round(score, 4)}
        for fb_id, score in sorted_results
    ]

    print(f"[SEARCH] Found {len(formatted_results)} matches from Qdrant.")
    return formatted_results

print("Search function updated to filter closed reports.")

import time
from google.cloud.firestore_v1.watch import ChangeType
from colorama import Fore, Style, init

def on_snapshot(col_snapshot, changes, read_time):
    for change in changes:
        doc = change.document
        doc_id = doc.id
        data = doc.to_dict() or {}

        # --- Handle Deletion ---
        if change.type == ChangeType.REMOVED:
            print(f"{Fore.YELLOW}\n[EVENT] Report Deleted | ID: {doc_id}")
            try:
                qdrant_id = generate_qdrant_id(doc_id)
                client.delete(collection_name=collection_name, points_selector=[qdrant_id])
                print(f"{Fore.YELLOW}[QDRANT] Successfully removed {doc_id} to prevent ghost matches.")

                # Start of update: Reverse cleanup from other reports that matched with the deleted report
                old_matches_in_deleted = data.get('matches', [])
                for match in old_matches_in_deleted:
                    matched_id = match.get('matched_report_id')
                    if matched_id:
                        matched_ref = db.collection('reports').document(matched_id)
                        matched_snap = matched_ref.get()
                        if matched_snap.exists:
                            matched_data = matched_snap.to_dict()
                            matched_matches = matched_data.get('matches', [])
                            filtered = [m for m in matched_matches if m.get('matched_report_id') != doc_id]
                            if len(filtered) != len(matched_matches):
                                matched_ref.update({'matches': filtered})
                                print(f"{Fore.YELLOW}[FIREBASE] Cleanup: Removed {doc_id} from {matched_id} matches.")
                # End of update
            except Exception as e:
                print(f"{Fore.RED}[ERROR] Error removing {doc_id}: {e}")

        # Start of update: Monitor closed status (MODIFIED)
        elif change.type == ChangeType.MODIFIED:
            current_status = data.get('status')
            ai_status = data.get('ai_status')

            if current_status == 'closed' and ai_status != 'cleanup_done':
                print(f"{Fore.BLUE}\n[EVENT] Report Closed | ID: {doc_id}")
                try:
                    # 1. Delete the vector from Qdrant to prevent ghost matches
                    qdrant_id = generate_qdrant_id(doc_id)
                    client.delete(collection_name=collection_name, points_selector=[qdrant_id])
                    print(f"{Fore.BLUE}[QDRANT] Successfully removed {doc_id} because it's closed.")

                    # 2. Reverse cleanup from other reports

                    existing_matches = data.get('matches', [])
                    for match in existing_matches:
                        matched_id = match.get('matched_report_id')
                        if matched_id:
                            matched_ref = db.collection('reports').document(matched_id)
                            matched_snap = matched_ref.get()
                            if matched_snap.exists:
                                matched_data = matched_snap.to_dict()
                                matched_matches = matched_data.get('matches', [])
                                filtered = [m for m in matched_matches if m.get('matched_report_id') != doc_id]
                                if len(filtered) != len(matched_matches):
                                    matched_ref.update({'matches': filtered})
                                    print(f"{Fore.BLUE}[FIREBASE] Cleanup: Removed closed report {doc_id} from {matched_id}.")

                    # 3. Update ai_status to prevent repeated cleanup on the same report
                    db.collection('reports').document(doc_id).update({'ai_status': 'cleanup_done'})
                    print(f"{Fore.BLUE}[FIREBASE] Marked {doc_id} as cleanup_done.")

                except Exception as e:
                    print(f"{Fore.RED}[ERROR] Failed to cleanup closed report {doc_id}: {e}")
        # --- End of update ---

        # --- Handle Addition ---
        elif change.type == ChangeType.ADDED:
            if data.get('ai_status') != 'pending':
                continue

            report_type = data.get('type')
            user_id = data.get('userId', 'unknown')
            item_dict = data.get('item', {})
            report_status = data.get('status', 'open') # Update here to fetch status for indexing

            print(f"{Fore.GREEN}\n[EVENT] New Pending Report | ID: {doc_id} | Type: {report_type} | User: {user_id}")

            try:
                db.collection('reports').document(doc_id).update({'ai_status': 'processing'})
                print(f"{Fore.GREEN}[FIREBASE] Locked document {doc_id} with status 'processing'.")

                print(f"{Fore.GREEN}[PROCESS] Extracting features and executing search...")
                matches = search_weighted_matches(item_dict, report_type, user_id, top_k=3)

                print(f"{Fore.GREEN}[PROCESS] Pushing vectors to Qdrant...")
                index_report_to_qdrant(doc_id, item_dict, report_type, user_id, report_status) # Update here to pass status for indexing

                db.collection('reports').document(doc_id).update({
                    'matches': matches,
                    'ai_status': 'completed'
                })
                print(f"{Fore.GREEN}[FIREBASE] Updated NEW report {doc_id} with {len(matches)} matches and status 'completed'.")

                if matches:
                    print(f"{Fore.GREEN}[MATCHING] Initiating symmetric update for {len(matches)} older report(s)...")
                    for match in matches:
                        matched_id = match['matched_report_id']
                        score = match['score']

                        old_doc_ref = db.collection('reports').document(matched_id)
                        old_doc = old_doc_ref.get()

                        if old_doc.exists:
                            old_data = old_doc.to_dict()
                            old_matches = old_data.get('matches', [])

                            if not any(m.get('matched_report_id') == doc_id for m in old_matches):
                                old_matches.append({
                                    "matched_report_id": doc_id,
                                    "score": score
                                })
                                old_matches = sorted(old_matches, key=lambda x: x['score'], reverse=True)
                                old_matches = old_matches[:3]

                                old_doc_ref.update({'matches': old_matches})
                                print(f"{Fore.GREEN}[FIREBASE] SYMMETRIC UPDATE: Added {doc_id} to {matched_id}.")
                            else:
                                print(f"{Fore.GREEN}[FIREBASE] Skip: {doc_id} already exists in {matched_id}.")

            except Exception as e:
                print(f"{Fore.RED}[ERROR] Failed to process {doc_id}: {e}")
                db.collection('reports').document(doc_id).update({'ai_status': 'error'})
                print(f"{Fore.RED}[FIREBASE] Reverted status of {doc_id} to 'error'.")

print("Initializing Dhallah AI Engine (v5 - Symmetric, Auto-Delete, Protect, Smart Pruning, Closed Cleanup)...")
print("Listening for incoming reports...")

reports_query = db.collection('reports')
query_watch = reports_query.on_snapshot(on_snapshot)

try:
    while True:
        time.sleep(1)
except KeyboardInterrupt:
    print(f"\n{Fore.RED}Stopping AI Engine...")
    query_watch.unsubscribe()
    print(f"{Fore.RED}Worker stopped safely.")